project_id = "jexrdkvrclqwdwnxboyn"

[functions.leads]
verify_jwt = false

[functions.callbacks]
verify_jwt = false

[functions.calendly-webhook]
verify_jwt = false

[functions.grego-chat]
verify_jwt = false
